package webCopy

import java.io.File
import edu.umro.ScalaUtil.FileUtil

object Config {

    /**
     * Used these URLs from browser to get list of all titles:
     *
     * http://141.214.124.203/rodevwiki/api.php?action=query&list=allpages&aplimit=500&apfrom=
     * http://141.214.124.203/rodevwiki/api.php?action=query&list=allpages&aplimit=500&apfrom=V
     */
    val pageTitleList = List(
        "Manuals %2B Tutorials",
        "CETPlan Patches: V361 17",
        "LOGWS",
        "Main Page",
        "Avs blog:new avs development and release structure",
        "LOGWS",
        "361 37 Readiness review May 25 2010",
        "361 38 Release Planning",
        "361 38 Release Planning - 1/11/11",
        "361 38 Release Planning - 1/14/11",
        "361 38 Testing Review Meeting",
        "AVS:API Reference",
        "AVS:AVSFIELD DATA OFFSET",
        "AVS:AVSFIELD POINTS OFFSET",
        "AVS:AVSPORT FIELD",
        "AVS:AVSadd float parameter",
        "AVS:AVSadd parameter",
        "AVS:AVSadd parameter prop",
        "AVS:AVSautofree output",
        "AVS:AVSbuild 2d field",
        "AVS:AVSbuild 3d field",
        "AVS:AVSbuild field",
        "AVS:AVSchoice number",
        "AVS:AVScolormap get",
        "AVS:AVScolormap set",
        "AVS:AVScommand",
        "AVS:AVSconnect widget",
        "AVS:AVScorout X wait",
        "AVS:AVScorout event wait",
        "AVS:AVScorout exec",
        "AVS:AVScorout init",
        "AVS:AVScorout input",
        "AVS:AVScorout mark changed",
        "AVS:AVScorout output",
        "AVS:AVScorout set sync",
        "AVS:AVScorout wait",
        "AVS:AVScorout wait,",
        "AVS:AVScreate input port",
        "AVS:AVScreate output port",
        "AVS:AVSdata alloc",
        "AVS:AVSdata free",
        "AVS:AVSfield alloc",
        "AVS:AVSfield copy points",
        "AVS:AVSfield data ptr",
        "AVS:AVSfield free",
        "AVS:AVSfield get dimensions",
        "AVS:AVSfield get extent",
        "AVS:AVSfield get int",
        "AVS:AVSfield get label",
        "AVS:AVSfield get labels",
        "AVS:AVSfield get mesh id",
        "AVS:AVSfield get minmax",
        "AVS:AVSfield get unit",
        "AVS:AVSfield get units",
        "AVS:AVSfield invalid minmax",
        "AVS:AVSfield make template",
        "AVS:AVSfield points ptr",
        "AVS:AVSfield reset minmax",
        "AVS:AVSfield set extent",
        "AVS:AVSfield set int",
        "AVS:AVSfield set labels",
        "AVS:AVSfield set mesh id",
        "AVS:AVSfield set minmax",
        "AVS:AVSfield set units",
        "AVS:AVSget unique id",
        "AVS:AVSinit from module list",
        "AVS:AVSinit modules",
        "AVS:AVSinitialize output",
        "AVS:AVSinput changed",
        "AVS:AVSload user data types",
        "AVS:AVSmark output unchanged",
        "AVS:AVSmessage",
        "AVS:AVSmodify float parameter",
        "AVS:AVSmodify parameter",
        "AVS:AVSmodify parameter prop",
        "AVS:AVSmodule from desc",
        "AVS:AVSmodule status",
        "AVS:AVSparameter changed",
        "AVS:AVSparameter visible",
        "AVS:AVSset compute proc",
        "AVS:AVSset destroy proc",
        "AVS:AVSset init proc",
        "AVS:AVSset input class",
        "AVS:AVSset module flags",
        "AVS:AVSset module name",
        "AVS:AVSset output class",
        "AVS:AVSset output flags",
        "AVS:AVSset parameter class",
        "AVS:AVSudata get double",
        "AVS:AVSudata get int",
        "AVS:AVSudata get real",
        "AVS:AVSudata get string",
        "AVS:AVSudata set double",
        "AVS:AVSudata set int",
        "AVS:AVSudata set real",
        "AVS:AVSudata set string",
        "AVS:Building AVS on VMS",
        "AVS:Dev Docs",
        "AVS:Mod Docs",
        "AVS:Net State",
        "AVS Docs",
        "Adaptive Radiotherapy Tools Page",
        "Adaptive Therapy Bookkeeping",
        "Alan's Old Project Page",
        "Alan's Project Page",
        "Applaundrylist",
        "Blog",
        "BugTracker Information",
        "Bug Fix Testing",
        "Bug Review April 15 2010",
        "Bug Review January 07 2010",
        "Bug Review June 30 2009",
        "Build Verification Tests",
        "CDA Design Review 11-03-2009",
        "CETPlan",
        "CETPlan-Patches",
        "CVSO v213",
        "CVSP 300 Release Notes",
        "CVSP v213",
        "Calc Model Information",
        "Clinic - Developers Communications Page",
        "Clinical Release Notes",
        "Config-blocks",
        "Configuring UMPlan 361 System",
        "Configuring blocks in Aria",
        "Convolution",
        "Convolution Relase Notes",
        "Convolution Release Notes",
        "Core D PPG Page",
        "Create IMRT QA",
        "Current Issues List",
        "Current Workarounds List",
        "Cvsp 213 Release Notes",
        "Cvsp 213 rel note",
        "Cvsp 300 rel note",
        "Cvspblog:added time log",
        "Cvspblog:ec correction for dose-to-points calcs",
        "Cvspblog:fixed out-of-bounds error in terma calc",
        "Cvspblog:fixed sc calculation grid",
        "Cvspblog:june 12 2006",
        "Cvspblog:machine file versioning",
        "Cvspblog:mlc sequence calcs - ea",
        "Cvspblog:send umoptim beam points calcs to linux cluster",
        "DCMEXP Installation",
        "DCMEXP Windows Installation",
        "DICIMP 1 0 0-rn-eng sqe",
        "DICIMP 1 0 2-rn-eng sqe",
        "DICIMP 1 0 3-rn-eng sqe",
        "DICOM",
        "DICOM Import User Manual",
        "DICOM Import to UMPlan",
        "DICOM Import to UMPlan Instructions",
        "DICOM Release Notes",
        "DMP v201",
        "DPM v201",
        "Daily Triage Agenda",
        "Daily Triage Log",
        "Daily Triage Meeting Minutes Log",
        "Dcmimp 1 0 04-rn-eng sqe",
        "Dcmimp 1 0 05-rn-eng sqe",
        "Dcmimp 1 0 06-rn-eng sqe",
        "Dcmimp 1 0 07-rn-eng sqe",
        "Dcmimp 1 0 08-rn-eng sqe",
        "Dcmimp 1 0 09-rn-eng sqe",
        "Dcmimp 1 0 10-rn-eng sqe",
        "Dcmimp 1 0 11-rn-eng sqe",
        "Dcmimp 1 0 12-rn-eng sqe",
        "Dcmimp 1 0 13-rn-eng sqe",
        "Dcmimp 1 0 14-rn-eng sqe",
        "Dcmimp 1 0 15-rn-eng sqe",
        "Dcmimp 1 0 16-rn-eng sqe",
        "Dcmimp 1 0 17-rn-eng sqe",
        "Dcmimp 1 0 18-rn-eng sqe",
        "Development on VMS",
        "Dicom:leademail",
        "Dicom:leadtoolscost",
        "Dicom:mergeemail",
        "Dicom Export Project Page",
        "DocFor",
        "Download Verification",
        "Dpmblog:machine file versioning",
        "ESB",
        "Editing the List of Scanning Machines for DICOM Import to UMPlan",
        "Export IMRT QA",
        "FAQ",
        "FDF2 Library",
        "Falcon:admin log",
        "Falcon:cluster admin",
        "Format",
        "GUI Design",
        "High level functional requirements",
        "How to get source code, build, and install",
        "Http://141.214.124.203/um-plan/v361:fixes",
        "IMRT Overview",
        "IMRT QA",
        "IMRT QA Plan Download",
        "IMRT QA Review",
        "IMRT QA Troubleshooting",
        "Import",
        "Information Setup",
        "Installing New Version of CVSP on Linux Cluster",
        "Installing TXD",
        "Installing UMPlan",
        "Installing UMPlan for Clinical Use",
        "Installing a new version of CVSP on Linux Cluster",
        "Installing for Clinical Use",
        "Installing the Commissioning Software",
        "JBoss",
        "JQM/UMPlan Integration",
        "JQM FAQ",
        "JQM FAQs",
        "Jqmfaq",
        "Kj 20070625",
        "Known Problems",
        "Location-Independant UMPlan",
        "Location Independent Configurations",
        "Log Viewer",
        "Log Viewer Developer Code Base Configuration",
        "Log Viewer Engineering Release Procedure",
        "Log Viewer Installation",
        "MITK Investigation",
        "MI REG2 testing meeting 2-jun-2011",
        "Machine Database Synchronization",
        "Machine Files Inventory",
        "Meplans",
        "Mlcleafposncorrection",
        "NEDIT on VMS",
        "New Projects",
        "Optimal 01-08-2010",
        "Optimal 01-15-2010",
        "Optimal 02-05-2010",
        "Optimal 02-12-2010",
        "Optimal 02-26-2010",
        "Optimal 03-05-2010",
        "Optimal 03-12-2010",
        "Optimal 03-26-2010",
        "Optimal Group",
        "Overview of CVS Source Code Repositories",
        "PersonalConquestServer",
        "Plan Anonymizer Tool",
        "Points v361 26",
        "Porting machine Files to Linux",
        "PrintPDF",
        "PrintPDF2",
        "Process Control",
        "QA Overview",
        "Quality Group",
        "Quality Group 13-MAY-2010",
        "Quality Group 17-FEB-2010",
        "Quality Group 17-MAR-2010",
        "Quality Group 24-FEB-2010",
        "Quality Group 24-MAR-2010",
        "Quality Group 27-MAY-2010",
        "Quality Group 29-APR-2010",
        "RadOnc Cluster Doc Wiki",
        "RadOnc Cluster Wiki",
        "Release Memo",
        "Release Memo for V361",
        "Release Memos",
        "Release Notes",
        "Release UMServices to SQE",
        "Releasing UMPlan to SQE",
        "Releasing to SQE",
        "Review of Rally Dev",
        "Sandbox:ManTemplate",
        "Scripts",
        "See DLM's notes.",
        "Sprint 2 Design Discussion 1-27-10",
        "Sprint 2 Engineering Release Note",
        "Sprint 2 Planning 2-04-10",
        "Sprint 3 Engineering Release Note",
        "Sprint 4 Engineering Release Note",
        "TXD",
        "TXD Documentation",
        "TXD FAQ",
        "TXD Fixes and Features",
        "TXD Testing",
        "TXD V200 100 Engineering Release Note",
        "TXD V200 101 Engineering Release Note",
        "TXD V200 102 Engineering Release Note",
        "TXD V200 103 Engineering Release Note",
        "TXD V200 104 Engineering Release Note",
        "TXD V200 82 Engineering Release Note",
        "TXD V200 84 Engineering Release Note",
        "TXD V200 86-A Engineering Release Note",
        "TXD V200 86 Engineering Release Note",
        "TXD V200 87 Engineering Release Note",
        "TXD V200 88 Engineering Release Note",
        "TXD V200 89 Engineering Release Note",
        "TXD V200 90 Engineering Release Note",
        "TXD V200 91 Engineering Release Note",
        "TXD V200 92 Engineering Release Note",
        "TXD V200 93 Engineering Release Note",
        "TXD V200 94 Engineering Release Note",
        "TXD V200 95 Engineering Release Note",
        "TXD V200 96 Engineering Release Note",
        "TXD V200 97 Engineering Release Note",
        "TXD V200 98 Engineering Release Note",
        "TXD V200 99 Engineering Release Note",
        "TXD V200 Engineering Release Procedure",
        "TXD V200 Project Page",
        "TXD V300 Developer Code Base Configuration",
        "TXD V300 Engineering Release Procedure",
        "Technology Reviews",
        "Testing",
        "Thread0 01-08-2010",
        "Thread0 01-11-2010",
        "Thread0 01-14-2010",
        "Thread0 01-15-2010",
        "Thread0 10-08-2009",
        "Thread0 11-12-2009",
        "Thread0 11-19-2009",
        "Thread0 12-03-2009",
        "Thread0 12-09-2009",
        "Thread0 12-10-2009",
        "Thread0 9-24-2009",
        "Thread0 Guiding Principles",
        "Thread0 Meeting Notes",
        "Thread 0",
        "Tools for Adaptive Radiotherapy Project Page",
        "Triage Minutes April 08 2011",
        "Triage Minutes April 10 2009",
        "Triage Minutes April 14 2009",
        "Triage Minutes April 1 2009",
        "Triage Minutes April 21 2009",
        "Triage Minutes April 22 2009",
        "Triage Minutes April 2 2009",
        "Triage Minutes April 3 2009",
        "Triage Minutes April 9 2009",
        "Triage Minutes August 20 2009",
        "Triage Minutes December 10 2009",
        "Triage Minutes December 11 2009",
        "Triage Minutes December 14 2009",
        "Triage Minutes December 15 2009",
        "Triage Minutes December 16 2009",
        "Triage Minutes December 17 2009",
        "Triage Minutes December 1 2009",
        "Triage Minutes December 4 2009",
        "Triage Minutes December 8 2009",
        "Triage Minutes December 9 2009",
        "Triage Minutes February 04 2010",
        "Triage Minutes February 12 2010",
        "Triage Minutes January 13 2010",
        "Triage Minutes June 01 2009",
        "Triage Minutes June 04 2009",
        "Triage Minutes June 16 2009",
        "Triage Minutes June 18 2009",
        "Triage Minutes June 19 2009",
        "Triage Minutes June 23 2009",
        "Triage Minutes June 29 2009",
        "Triage Minutes March 10 2009",
        "Triage Minutes March 10 2011",
        "Triage Minutes March 11 2009",
        "Triage Minutes March 12 2009",
        "Triage Minutes March 13 2009",
        "Triage Minutes March 17 2009",
        "Triage Minutes March 17 2011",
        "Triage Minutes March 18 2009",
        "Triage Minutes March 19 2009",
        "Triage Minutes March 1 2011",
        "Triage Minutes March 20 2009",
        "Triage Minutes March 23 2009",
        "Triage Minutes March 24 2009",
        "Triage Minutes March 24 2011",
        "Triage Minutes March 25 2009",
        "Triage Minutes March 27 2009",
        "Triage Minutes March 2 2011",
        "Triage Minutes March 31 2009",
        "Triage Minutes March 3 2011",
        "Triage Minutes March 6 2009",
        "Triage Minutes March 8 2011",
        "Triage Minutes May 12 2009",
        "Triage Minutes May 18 2011",
        "Triage Minutes May 26 2009",
        "Triage Minutes May 28 2009",
        "Triage Minutes May 31 2011",
        "Triage Minutes November 20 2009",
        "Triage Minutes September 30 2009",
        "Troubleshooting",
        "Troubleshooting IMRT QA",
        "Troubleshooting TXD",
        "Ttverrors",
        "Txd:config-file",
        "U-M News Feed",
        "UMOPT/Points",
        "UMPLAN-NG December 04 2009",
        "UMPLANCFGDIR",
        "UMPlan",
        "UMPlan 361 System Page",
        "UMPlan Development Wiki",
        "UMPlan Documentation",
        "UMPlan FAQ",
        "UMPlan V400 Page",
        "UMPlan XML Toolkit manual",
        "UMPlan v361",
        "UMROAMQP",
        "UMROAMQP Design",
        "UMServices Page",
        "Umdevdocs:dicom imp util:gui",
        "Umdevdocs:machine synch tool:export lin",
        "Umdevdocs:toolkit xml:2ddose xml",
        "Umdevdocs:toolkit xml:beam tkxml",
        "Umdevdocs:toolkit xml:beamnorm xml",
        "Umdevdocs:toolkit xml:calc2d xml",
        "Umdevdocs:toolkit xml:calc xml",
        "Umdevdocs:toolkit xml:case xml",
        "Umdevdocs:toolkit xml:cut xml",
        "Umdevdocs:toolkit xml:dataset xml",
        "Umdevdocs:toolkit xml:dose3d xml",
        "Umdevdocs:toolkit xml:geom xml",
        "Umdevdocs:toolkit xml:patorient xml",
        "Umdevdocs:toolkit xml:plan xml",
        "Umdevdocs:toolkit xml:structure xml",
        "Umdevdocs:usecase:select mkeydb import",
        "Ump361 10-changed",
        "Ump361 11-RN",
        "Ump361 11-changed",
        "Ump361 13-RN",
        "Ump361 13-changed",
        "Ump361 14-RN",
        "Ump361 14-changed",
        "Ump361 15-RN",
        "Ump361 15-changed",
        "Ump361 16-changed",
        "Ump361 16-rn-eng sqe",
        "Ump361 17-rn-eng sqe",
        "Ump361 18-changed",
        "Ump361 18-rn-eng sqe",
        "Ump361 19-rn-eng sqe",
        "Ump361 20-rn-eng sqe",
        "Ump361 21-changed",
        "Ump361 21-rn-eng sqe",
        "Ump361 22-changed",
        "Ump361 22-rn-eng sqe",
        "Ump361 23-changed",
        "Ump361 23-rn-eng sqe",
        "Ump361 24-changed",
        "Ump361 24-rn-eng sqe",
        "Ump361 25-changed",
        "Ump361 25-rn-eng sqe",
        "Ump361 26-rn-eng sqe",
        "Ump361 27-rn-eng sqe",
        "Ump361 29-rn-eng sqe",
        "Ump361 30-rn-eng sqe",
        "Ump361 31-rn-eng sqe",
        "Ump361 32-rn-eng sqe",
        "Ump361 33-rn-eng sqe",
        "Ump361 34-rn-eng sqe",
        "Ump361 35-rn-eng sqe",
        "Ump361 36-rn-eng sqe",
        "Ump361 37-rn-eng sqe",
        "Ump361 38-changed",
        "Ump361 38-rn-eng sqe",
        "Ump361 39-patched",
        "Ump361 39-rn-eng sqe",
        "Ump361 39b-patched",
        "Ump361 39c-patched",
        "Ump361 7-changed",
        "Ump361 9-changed",
        "Umpfaq",
        "Umplan blog dicomrt",
        "Umws:fileexportws",
        "Umws:jqm",
        "Umws:patdbws",
        "Umws:toolkitws",
        "Umws:umrodbserver",
        "Umws:umrologin",
        "Umws:umrottserver",
        "User Manual",
        "Using Log Viewer",
        "V300 07 Engineering Release Note",
        "V300 08 Engineering Release Note",
        "V300 09 Engineering Release Note",
        "V300 10 Engineering Release Note",
        "V300 11 Engineering Release Note",
        "V300 12 Engineering Release Note",
        "V300 13 Engineering Release Note",
        "V300 14 Engineering Release Note",
        "V300 15 Engineering Release Note",
        "V300 16 Engineering Release Note",
        "V300 17 Engineering Release Note",
        "V300 18 Engineering Release Note",
        "V300 19 Engineering Release Note",
        "V300 21 Engineering Release Note",
        "V300 22 Engineering Release Note",
        "V300 23 Engineering Release Note",
        "V300 24 Engineering Release Note",
        "V300 25 Engineering Release Note",
        "V300 26 Engineering Release Note",
        "V300 27 Engineering Release Note",
        "V300 28 Engineering Release Note",
        "V300 29 Engineering Release Note",
        "V300 30 Engineering Release Note",
        "V361",
        "V361 20-dlm",
        "V361 Known Problems",
        "V361 Testing",
        "V361blog:created export imrt qa",
        "V361blog:machine file versioning for cvsp and dpm",
        "V361blog:utility to update umplan config symbols from umplan config.xml",
        "V361blog:v361 8 imrt cvsp calculation using mlc and out map",
        "V40 Release Planning 23 June 2011",
        "VIM on VMS",
        "Varis Access Web Service",
        "Version 1.0 Engineering Release Notes",
        "Web Service Interface Descriptions",
        "Wiki",
        "XML Toolkit",
        "Xform file format")

    val pagePrefix = """<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">""" + "\n"

    val host = "141.214.124.203"

    val urlPrefix = "/rodevwiki/index.php"
    //http://141.214.124.203/rodevwiki/index.php/

    val redundantPrefix = "http://141.214.124.203" + urlPrefix

    val outputDir = new File("D:\\tmp\\mediawiki\\content\\umrosw")

    // def pageTitleToURL(title: String): String = "http://" + host + urlPrefix + "/" + (title.replace(' ', '_') + "&printable=yes")

    def pageTitleToURL(title: String): String = "http://" + host + urlPrefix + "?title=" + (title.replace(' ', '_') + "&printable=yes")

    def pageTitleToFile(title: String): File = new File(outputDir, FileUtil.replaceInvalidFileNameCharacters(title.replace(' ', '_'), '_'))

    /**
     * For testing and development only.
     */
    def main(args: Array[String]): Unit = {
        println("Starting")
        println("\nExiting...")
        System.exit(0)
    }

}